# Generated by Django 4.0.6 on 2022-07-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('zipcode', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images')),
                ('file_uplode', models.FileField(upload_to='files')),
                ('is_created', models.DateTimeField(auto_now_add=True)),
                ('is_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
