# Generated by Django 4.0.6 on 2022-07-14 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='file_uplode',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
