# Generated by Django 4.0.6 on 2022-07-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_remove_profile_file_uplode_remove_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
